### ISSUE TITLE
Toggle Switches in Tile property sheets are invisible

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#175]
This is a problem with this section in `base.css`

```css
.tile .property-sheet * {
    /* TODO figure out exactly what needs to be set */
    -fx-background-color: transparent;
}
```

This section is intended to make the background of the sheet transparent to match the background color of the tile.

If we're going to show tile preferences in dialog windows, this is a non-issue
